### ISSUE TITLE
После ввода /tsp start в майне, это спамится в консоль

### ISSUE THREAD

**Issue by r41dy** [thecreeez/MGBridge#1]
[16:47:05 WARN]: [thesecretplugin] Task #6 for thesecretplugin v1.0-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.NamespacedKey.asString()'
	at net.tcz.mc.gmodconnection.BridgeScheduler.run(BridgeScheduler.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1285) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:429) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1237) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1047) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by thecreeez** [comment]
Версия майнкрафта/джавы/спигота
